name: Docker Image CI

on:
  push:
    branches:
      - develop # Altere para o branch que desejar monitorar
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Login no Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 2: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Build e Push usando `docker/build-push-action`
      - name: Build and Push Docker images
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bot-whatsapp:latest
            ${{ secrets.DOCKER_USERNAME }}/bot-whatsapp:${{ github.run_number }}-${{ github.sha }}
          build-args: |
            TOKEN_META=${{ secrets.TOKEN_META }}
            PHONE_NUMBER_ID=${{ secrets.PHONE_NUMBER_ID }}
            VERIFY_TOKEN=${{ secrets.VERIFY_TOKEN }}